name: Build Release Artifacts
on:
  release:
    types: [created]
jobs:
  build-deb:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '14'
      - uses: DeLaGuardo/setup-clojure@2.0
        with:
          lein: 2.9.1
      - name: Get $RELEASE_VERSION
        run: echo ::set-env name=RELEASE_VERSION::${GITHUB_REF:11}
      - run: lein uberjar
      - name: jpackage
        run: |
          mkdir target/input
          mv target/uberjar/gif-captioner-standalone.jar target/input
          jpackage @jpackage/common --app-version $RELEASE_VERSION --linux-shortcut
      - uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: target/input/gif-captioner-standalone.jar
          asset_name: gif-captioner-standalone.jar
          asset_content_type: application/jar-archive
      - uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: target/output/gif-captioner_${{ env.RELEASE_VERSION }}-1_amd64.deb
          asset_name: gif-captioner_${{ env.RELEASE_VERSION }}-1_amd64.deb
          asset_content_type: application/vnd.debian.binary-package
  build-dmg:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '14'
      - uses: DeLaGuardo/setup-clojure@2.0
        with:
          lein: 2.9.1
      - name: Get $RELEASE_VERSION
        run: echo ::set-env name=RELEASE_VERSION::${GITHUB_REF:11}
      - run: lein uberjar
      - name: jpackage
        run: |
          mkdir target/input
          mv target/uberjar/gif-captioner-standalone.jar target/input
          jpackage @jpackage/common --app-version $RELEASE_VERSION
      - uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: target/output/gif-captioner-${{ env.RELEASE_VERSION }}.dmg
          asset_name: gif-captioner-${{ env.RELEASE_VERSION }}.dmg
          asset_content_type: application/x-apple-diskimage
  build-exe:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '14'
      - name: Install Leiningen
        run: |
          iwr https://raw.githubusercontent.com/technomancy/leiningen/stable/bin/lein.bat -OutFile lein.bat
          .\lein self-install
      - name: Get $RELEASE_VERSION
        shell: powershell
        run: |
          $REL=$Env:GITHUB_REF.Substring(11)
          echo "::set-env name=RELEASE_VERSION::$REL"
      - run: .\lein uberjar
      - name: jpackage
        shell: powershell
        run: |
          mkdir target\input
          mv target\uberjar\gif-captioner-standalone.jar target\input
          jpackage @jpackage/common --app-version $Env:RELEASE_VERSION --win-menu
      - uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: target/output/gif-captioner-${{ env.RELEASE_VERSION }}.exe
          asset_name: gif-captioner-${{ env.RELEASE_VERSION }}.exe
          asset_content_type: application/vnd.microsoft.portable-executable
